### PR TITLE
Keyboard Dismiss options in Add event screen

### PR DESCRIPTION
**Pull request by SaurabhJamadagni**
- This PR is associated to issue #6 
- It introduces the use of `.scrollDismissesKeyboard` modifier to dismiss the keyboard when the user begins to scroll.
  - This modifier is only applicable to iOS 16 and above. Thus a different solution has to be implemented to fall back on.
  - I have currently kept the tap gesture even if the device has iOS 16+ so as to maintain uniformity. But if it isn't required, I could definitely take it out.
- The other solution creates a sort of container over the Form so that an onTapGesture ends editing. This way, no other input components interfere with the tap gesture.
- This allows to keep the swipe down gesture to dismiss the entire sheet like before to avoid confusion.
- PR also changes keyboard key to say `done` instead of `return`.
- I was unsure which file I should put the `Background Struct` in commit 5be601b02e42fffd739d4e3845f74754bbbc178b line 137.
- If it requires creating a new file, please let me know.
- Also, open to any suggestion or different implementation that might come to mind.

@vickipetrova could you please take a look at these changes? Thank you 😄

### CODE REVIEW

**Comment by vickipetrova** [comment]
Hey Saurabh @SaurabhJamadagni ! 😊 I just went through the PR - everything's working as expected. Thank you so much, I tried so many times to fix this and even me and Jordi couldn't figure it out together. Apologies for the long delay - I recently finished my third year at uni so I had some more free time now.

**Comment by vickipetrova** [comment]
Hi again! @SaurabhJamadagni Today, I noticed that the tap gesture to close the keyboard was actually blocking all other tap gestures on the Form. This meant that users couldn't perform any other tap gestures (ie selecting a date or category). So I removed the tap gesture to dismiss the keyboard. I haven't been able to come up with a solution for this. Any ideas?

**Comment by SaurabhJamadagni** [comment]
>  I haven't been able to come up with a solution for this. Any ideas?

Hey @vickipetrova! That's an interesting problem. I am surprised I missed it. I am between a move currently. I'll look into it soon. Sorry about the delay. Let me know if you come up with something as well. Would love to know what I could have done better. 😊

**Comment by vickipetrova** [comment]
Good luck with the move, I haven't been able to figure it out.

**Pull request merged**
